Add EXE_FILE_NAME and INSTALLCOPY to src/CMakeLists.txt to facilitate integration testing
geoschem/GCHP pull request #276
Opened 2022-12-22 16:36 UTC by yantosca

This PR modifies the `src/CMakeLists.txt` so that:
1. The GCHP executable file can be assigned a name other than "gchp" (e.g. `-DEXE_FILE_NAME=gchp.rrtmg`)
2. The GCHP executable file can be placed in a folder other than the run directory
(e.g. `-DRUNDIR='' -DINSTALLCOPY=/path/to/installation`)
These features are already present in GEOS-Chem Classic, but are also needed in GCHP to facilitate integration testing.

Also updated the `CHANGELOG.md` accordingly.

This PR should be merged concurrently with https://github.com/geoschem/geos-chem/pull/1565

GCHP integration tests are in progress.

2022-12-22 17:01 UTC, yantosca commented
GCHP compilation tests succeeded and the gchp executable files were copied to the `exe_files` subfolder of the integration test root directory:
```console
==============================================================================
GCHP: Compilation Test Results

GCClassic #c7c4f1a Now allow -DINSTALLCOPY and -DEXE_FILE_NAME settings for GCHP
GEOS-Chem #b590a8cdb Remove check for results log in intTestExecute.sh scripts
HEMCO     #1e8e648 Merge branch 'feature/use_mapl_undef_for_hco_missval_if_gchp_or_geos' into dev/3.6.0

Number of compilation tests: 2

Submitted as SLURM job: 36546132
==============================================================================
 
Compiliation tests:
------------------------------------------------------------------------------
GCHP................................................Configure & Build.....PASS
GCHP with RRTMG.....................................Configure & Build.....PASS
 
Summary of compilation test results:
------------------------------------------------------------------------------
Complilation tests passed:        2
Complilation tests failed:        0
Complilation tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All compilation tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2023-01-11 19:08 UTC, lizziel requested changes
This looks good except the submodule change is part of the PR. Could you remove that? We merge in the submodule updates separately.

2023-01-11 19:38 UTC, yantosca commented
@lizziel I can remove it.  I might have to put a new branch on top of dev/14.1.0 to account for several changes in e.g. HEMCO that were more recent than this branch.

2023-01-11 19:49 UTC, closed without merging

2023-01-11 19:57 UTC, yantosca commented
@lizziel: Now superseded by PR #281.  All submodule updates have been removed.