dd submodule update issue template
geoschem/GCHP pull request #307
Opened 2023-03-30 21:00 UTC by lizziel

### Name and Institution (Required)

Name:
Institution:

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### Describe the update

Please provide a clear and concise overview of the update.

### Expected changes

Please provide details on how this update will impact model output and include plots or tables as needed.

### Reference(s)

If this is a science update, please provide a literature citation.

### Related Github Issue(s)

Please link to the corresponding Github issue here. If fixing a bug, there should be an issue describing it with steps to reproduce.

2023-03-30 21:07 UTC, yantosca requested changes
Looks good.  I just had one question about the template checkboxes.

2023-03-30 21:07 UTC, yantosca commented on .github/ISSUE_TEMPLATE/submodule-updates.md
> +* [ ] https://github.com/geoschem/geos-chem/pull/834
Should we make example numbers like pull/xxxxand note that we should replace then xxxx with the issue number?

2023-04-11 15:15 UTC, lizziel commented on .github/ISSUE_TEMPLATE/submodule-updates.md
> +* [ ] https://github.com/geoschem/geos-chem/pull/834
Will do.

2023-04-11 15:44 UTC, yantosca approved these changes
Good to merge

2023-04-12 17:04 UTC, merged