Add capability for TOMAS simulations in GCHP
geoschem/GCHP pull request #359
Opened 2023-12-05 21:30 UTC by msulprizio

### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Describe the update

This pull request adds the option to run GCHP with TOMAS as originally implemented by @BettyCroft in:

- https://github.com/geoschem/GCHP/pull/252

This pull request should be merged alongside:
- https://github.com/geoschem/geos-chem/pull/2060
- https://github.com/geoschem/HEMCO/pull/251

2023-12-05 21:43 UTC, yantosca requested changes
This looks mostly good to merge, pending minor fixes as noted.

Also: The HEMCO submodule only has 2 files changed but the HEMCO PR #251 contains changes 3 files.  We'll need to point to the updated commit in the HEMCO submodule.

2023-12-05 21:43 UTC, yantosca commented on CHANGELOG.md
> +>>>>>>> origin/main
Delete leftover slug from the git merge

2023-12-06 13:46 UTC, msulprizio commented on CHANGELOG.md
> +>>>>>>> origin/main
This is now fixed in https://github.com/geoschem/GCHP/pull/359/commits/41c136fc1e725e98a54216d7df2bcdb94f7fbaa3.

2023-12-06 16:38 UTC, yantosca approved these changes
Now good to merge!

2023-12-06 17:34 UTC, merged