Fix GCHPctmEnv small numerical bugs
geoschem/GCHP pull request #456
Opened 2024-10-30 22:15 UTC by yuanjianz

### Name and Institution (Required)

Name: Yuanjian Zhang
Institution: WashU

### Describe the update

1. Correct dry mass flux derivation.
2. Correct upwardsMassflux sign.

### Expected changes

1. Dry mass flux will be slightly smaller than before but is expected.
2. UpwardsMassflux diagnostic will correctly be positive = "up"

### Related Github Issue

#445 #455

2024-11-12 18:45 UTC, lizziel commented
Update #1 affects only GCHP runs that import mass fluxes from offline meteorology which makes this a zero diff update for benchmarking. I will therefore put milestone 14.5.1.

2024-11-15 19:21 UTC, lizziel requested changes
Please also update the changelog with the updates.

2024-11-15 19:21 UTC, lizziel commented on src/GCHP_GridComp/GCHPctmEnv_GridComp/GCHPctmEnv_GridCompMod.F90
> +         ! Flip vertical so that GCHP diagnostic level is follwing GEOS-Chem convetion
Typo in 'following'

2024-11-15 20:02 UTC, yuanjianz commented on src/GCHP_GridComp/GCHPctmEnv_GridComp/GCHPctmEnv_GridCompMod.F90
> +         ! Flip vertical so that GCHP diagnostic level is follwing GEOS-Chem convetion
Typo fixed and ChangeLog Updated

2024-11-18 18:17 UTC, lizziel approved these changes

2024-12-04 15:53 UTC, lizziel commented
@yuanjianz, I am rebasing to avoid merge conflicts and streamline the git history when I bring this into dev/no-diff-to-benchmark.

2024-12-05 15:42 UTC, merged